### ISSUE TITLE
Add Profile Section

### ISSUE THREAD

**Issue by Sujal-Sahu** [matrixiocommunity/inotebook#1]
Add the Profile section at top-right corner where users can see his short description about notes and their updated time with note title and can add anything creative you can do.

**Comment by Sakshi-75** [comment]
Hi @Sujal-Sahu ,
Can I work on this?

**Comment by Sujal-Sahu** [comment]
> Hi @Sujal-Sahu , Can I work on this?

Sure @Sakshi-75 go for it.

**Comment by Sakshi-75** [comment]
Hi @Sujal-Sahu ,
I had a few questions:
1. The right side of the navbar seems a bit crowded already with the search and the dark mode toggle, wouldn't it be better to have Profile as part of the list on the left side? If no, can you let me know where exactly you want the Profile button?
2. Can you tell me how to start up the backend? I'm not able to test things out properly without it.

**Comment by Sujal-Sahu** [comment]
> Hi @Sujal-Sahu , I had a few questions:
> 
> 1. The right side of the navbar seems a bit crowded already with the search and the dark mode toggle, wouldn't it be better to have Profile as part of the list on the left side? If no, can you let me know where exactly you want the Profile button?
> 2. Can you tell me how to start up the backend? I'm not able to test things out properly without it.

Sorry for late reply due to festivals, Actually you can add the profile option at right side of search bar so search bar and the dark mode toggle will shift towards left and you can start the backend using npm run both command so frontend and backend both will work together and also you can check package.json file in which i has mentioned the ''both'' command using concurrently module.

**Comment by Sakshi-75** [comment]
Hi @Sujal-Sahu ,
For some reason none of my backend requests are getting successfully executed. I'm getting error "net::ERR_CONNECTION_REFUSED". As a result, I'm not able to test things out on my local. Even to see the home page I had to manually add the token in my local storage.
I've added the Profile section and it's routing. As for now, I've put the same code on that page as is there on the notes page's 'Your notes' section but I'm unable to add anything further as I'm not able to create any notes.
This the WIP PR I've raised: #5 
Can you help me out with the backend calls?

**Comment by Sujal-Sahu** [comment]
> Hi @Sujal-Sahu , For some reason none of my backend requests are getting successfully executed. I'm getting error "net::ERR_CONNECTION_REFUSED". As a result, I'm not able to test things out on my local. Even to see the home page I had to manually add the token in my local storage. I've added the Profile section and it's routing. As for now, I've put the same code on that page as is there on the notes page's 'Your notes' section but I'm unable to add anything further as I'm not able to create any notes. This the WIP PR I've raised: #5 Can you help me out with the backend calls?

Actually i think i used mongo db database for storing the notes so if you doesn't have mongo db environment in your laptop or you doesn't start the mongo db using mongod and mongo command in command shell so it gives connection error because it is not able to make the connection with database.

**Comment by Sujal-Sahu** [comment]
hey @Sakshi-75  please reply if it works or not so i can get what is the real issue?

**Comment by subinsk** [comment]
If @Sakshi-75 is not working, can you assign this to me @Sujal-Sahu ?

**Comment by Sujal-Sahu** [comment]
Hey @Sakshi-75  please reply are you working on requested changes or not?

**Comment by Sakshi-75** [comment]
Hi @Sujal-Sahu , I'm unwell and this won't be able to continue working on this.
Since it is a time constrained issue, please assign it to someone else.

**Comment by Sujal-Sahu** [comment]
Okk @Sakshi-75 , but really you did a great work, be continue this spirit.

**Comment by Sujal-Sahu** [comment]
@subinsk  please work on this issue.

**Comment by subinsk** [comment]
Okay on it! @Sujal-Sahu
