### ISSUE TITLE
Add functionality for Search Option in backend

### ISSUE THREAD

**Issue by Sujal-Sahu** [matrixiocommunity/inotebook#2]
A search bar is present in navbar but it doesn't perform any functionality now so Create an API for search option in backend so it returns the notes with titles that are matching with the text present in search bar.

**Comment by subinsk** [comment]
Can you assign this to me @Sujal-Sahu ?

**Comment by subinsk** [comment]
I have implemented it, you can view in the pull request #6

**Comment by Sujal-Sahu** [comment]
Great @subinsk
