### ISSUE TITLE
Improve styling at login page

### ISSUE THREAD

**Issue by Sujal-Sahu** [matrixiocommunity/inotebook#4]
Now login and signup pages are working perfectly but have to improve the CSS to this page so it is looking nice and attractive.

**Comment by srijoy-paul** [comment]
Hey @Sujal-Sahu can you assign this task?

**Comment by Sujal-Sahu** [comment]
> Hey @Sujal-Sahu can you assign this task?

yes @srijoy-paul go for it.

**Comment by Sujal-Sahu** [comment]
Hey @srijoy-paul  are you working on this?

**Comment by srijoy-paul** [comment]
Hey @Sujal-Sahu I am working on it today, was busy with other tasks

**Comment by nik25s** [comment]
Hey! @Sujal-Sahu assign this task

**Comment by Sujal-Sahu** [comment]
Hey @srijoy-paul due to time constraint and not PR from your side, i assign this task to @nik25s . so @nik25s please work on it and complete it as soon as possible.
